version: '3.7'
services:
  web:
    container_name: '${CURRENT_PROJECT_NAME}_web'
    build: ./docker/webserver
    depends_on:
      - db
    networks:
      - private
    ports:
      - '${PORT_APACHE}:80'
    volumes:
      - './:/var/www/html:Z'
  db:
    container_name: '${CURRENT_PROJECT_NAME}_mysql'
    image: mariadb
    networks:
      - private
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - '${PORT_MYSQL}:3306'
    volumes:
      - './docker/data:/var/lib/mysql'
      - './docker/mysql/db.sql:/docker-entrypoint-initdb.d/dump.sql'
    command:
      - '--default-authentication-plugin=mysql_native_password'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${CURRENT_PROJECT_NAME}_phpmyadmin'
    depends_on:
      - db
    networks:
      - private
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '${PORT_PHPMYADMIN}:80'
networks:
  private:
    driver: bridge
